In [5]:
import pandas as pd
df = pd.read_csv("data/marvel_rivals_stats.csv")

In [3]:
print(df)

                     hero        role  matches  win_rate  MVPs  SVPs  \
0            Adam Warlock  Strategist     43.5      42.3     0     1
1                  Angela    Vanguard      1.8       5.6     0     1
2           Black Panther     Duelist     16.4      44.5     0     0
3             Black Widow     Duelist      4.7      42.6     0     0
4                   Blade     Duelist     10.2      40.2     1     0
5            Bruce Banner    Vanguard      1.1       9.1     0     0
6         Captain America    Vanguard     17.4      58.6     0     0
7          Cloak & Dagger  Strategist     14.1      41.1     1     0
8               Daredevil     Duelist      1.9       0.0     0     0
9      Deadpool (Duelist)     Duelist      0.0       0.0     0     0
10  Deadpool (Strategist)  Strategist      0.0       0.0     0     0
11    Deadpool (Vanguard)    Vanguard     29.4      51.0     1     1
12         Doctor Strange    Vanguard    814.4      51.1    83   100
13        Elsa Bloodstone     Duelist      0.0       0.0     0     0
14             Emma Frost    Vanguard     69.2      36.0     3     4
15                 Gambit  Strategist    107.7      48.2     5     9
16                  Groot    Vanguard     33.1      46.5     2     2
17                Hawkeye     Duelist      1.7      70.6     0     0
18                   Hela     Duelist     26.5      46.8     0     1
19            Human Torch     Duelist      3.2      31.2     0     0
20        Invisible Woman  Strategist     43.6      48.6     0     0
21              Iron Fist     Duelist      3.3      15.2     0     0
22               Iron Man     Duelist      6.6      71.2     0     0
23    Jeff The Land Shark  Strategist     14.2      43.7     0     0
24                   Loki  Strategist     69.1      50.9     4     2
25              Luna Snow  Strategist      0.0       0.0     0     0
26                  Magik     Duelist     12.0      58.3     0     0
27                Magneto    Vanguard     99.6      48.9     2     6
28                 Mantis  Strategist     33.6      67.9     1     1
29       Mister Fantastic     Duelist      5.6      39.3     1     0
30            Moon Knight     Duelist     10.9      30.3     1     0
31                  Namor     Duelist     18.6      45.2     1     2
32            Peni Parker    Vanguard     18.5      41.1     1     0
33                Phoenix     Duelist      3.3      33.3     0     0
34               Psylocke     Duelist     26.5      42.3     0     1
35         Rocket Raccoon  Strategist     31.5      35.9     1     1
36                  Rogue    Vanguard      1.9      31.6     0     0
37          Scarlet Witch     Duelist     42.7      59.7     4     0
38             Spider-Man     Duelist      2.0      50.0     0     0
39          Squirrel Girl     Duelist      8.4      35.7     0     1
40              Star-Lord     Duelist      3.9      35.9     0     0
41                  Storm     Duelist    183.0      61.0    19    12
42           The Punisher     Duelist      3.6      27.8     0     0
43              The Thing    Vanguard     40.5      40.5     1     5
44                   Thor    Vanguard     76.5      56.9     9     5
45                 Ultron  Strategist     82.1      51.9     7     5
46                  Venom    Vanguard      8.9      39.3     0     0
47              White Fox  Strategist      1.0     100.0     0     0
48         Winter Soldier     Duelist      5.9      69.5     0     0
49              Wolverine     Duelist     17.4      66.1     0     0

    Damage/Min  Healing/Min   K/D  K/D/A
0          412         1230  0.78   1.88
1          606            0  0.78   1.11
2          673            0  1.49   1.49
3          677            0  1.80   1.96
4         1149          182  1.79   2.23
5          555            0  0.75   1.00
6          602            5  1.59   1.70
7          524         1387  1.70   3.47
8          486           12  0.67   0.67
9            0            0  0.00   0.00
10           0            0  0.00   0.00
11         922          185  2.38   3.24
12        1069            0  2.88   3.12
13           0            0  0.00   0.00
14         987            0  2.19   2.54
15         578         1891  2.16   5.60
16         985           14  2.17   2.31
17        1240            0  2.80   3.40
18        1166            0  2.51   2.69
19         859            0  1.44   1.44
20         475         1305  1.27   2.97
21         508           37  0.74   0.74
22         731            0  2.29   2.29
23         441         1116  1.19   3.20
24         515         1189  1.80   4.45
25           0            0  0.00   0.00
26         729            0  1.73   1.74
27         995            0  2.02   2.44
28         430         1157  1.20   3.46
29         930            0  1.35   1.50
30        1078            8  1.32   1.36
31        1183            0  2.74   2.93
32        1181          209  3.28   4.61
33         968           76  1.50   1.54
34         739            0  1.66   1.66
35         243         1514  1.14   4.25
36         779          150  2.23   3.08
37        1203            0  3.23   3.49
38         488            0  1.25   1.25
39        1159            0  2.26   2.64
40         586            0  1.34   1.34
41        1268            0  2.94   5.47
42         609            0  0.88   0.88
43        1148            0  2.04   2.80
44        1057            0  2.73   3.21
45         643         1516  2.54   7.08
46         702            0  1.60   1.87
47        1179         1403  7.00  15.33
48         871            0  1.72   2.40
49         854           68  1.23   1.32

In [13]:
df.groupby("role")["matches"].sum()

role
Duelist        418.3
Strategist     440.4
Vanguard      1212.3
Name: matches, dtype: float64

In [6]:
df[(df["matches"]>=10.0) & (df["role"] == "Vanguard")]

,hero,role,matches,win_rate,MVPs,SVPs,Damage/Min,Healing/Min,K/D,K/D/A
6,Captain America,Vanguard,17.4,58.6,0,0,602,5,1.59,1.70
11,Deadpool (Vanguard),Vanguard,29.4,51.0,1,1,922,185,2.38,3.24
12,Doctor Strange,Vanguard,814.4,51.1,83,100,1069,0,2.88,3.12
14,Emma Frost,Vanguard,69.2,36.0,3,4,987,0,2.19,2.54
16,Groot,Vanguard,33.1,46.5,2,2,985,14,2.17,2.31
27,Magneto,Vanguard,99.6,48.9,2,6,995,0,2.02,2.44
32,Peni Parker,Vanguard,18.5,41.1,1,0,1181,209,3.28,4.61
43,The Thing,Vanguard,40.5,40.5,1,5,1148,0,2.04,2.80
44,Thor,Vanguard,76.5,56.9,9,5,1057,0,2.73,3.21

In [23]:
df[(df["win_rate"] >= 50.0) & (df["matches"] >= 10.0)].sort_values("win_rate", ascending=False)

,hero,role,matches,win_rate,MVPs,SVPs,Damage/Min,Healing/Min,K/D,K/D/A
28,Mantis,Strategist,33.6,67.9,1,1,430,1157,1.20,3.46
49,Wolverine,Duelist,17.4,66.1,0,0,854,68,1.23,1.32
41,Storm,Duelist,183.0,61.0,19,12,1268,0,2.94,5.47
37,Scarlet Witch,Duelist,42.7,59.7,4,0,1203,0,3.23,3.49
6,Captain America,Vanguard,17.4,58.6,0,0,602,5,1.59,1.70
26,Magik,Duelist,12.0,58.3,0,0,729,0,1.73,1.74
44,Thor,Vanguard,76.5,56.9,9,5,1057,0,2.73,3.21
45,Ultron,Strategist,82.1,51.9,7,5,643,1516,2.54,7.08
12,Doctor Strange,Vanguard,814.4,51.1,83,100,1069,0,2.88,3.12
11,Deadpool (Vanguard),Vanguard,29.4,51.0,1,1,922,185,2.38,3.24
24,Loki,Strategist,69.1,50.9,4,2,515,1189,1.80,4.45

In [4]:
df.groupby("role")["win_rate"].mean()

role
Duelist       40.668000
Strategist    44.208333
Vanguard      39.707692
Name: win_rate, dtype: float64

In [10]:
df[(df["matches"] >= 10) & (df["role"] == "Duelist")].sort_values(by="MVPs", ascending=False)

,hero,role,matches,win_rate,MVPs,SVPs,Damage/Min,Healing/Min,K/D,K/D/A
41,Storm,Duelist,183.0,61.0,19,12,1268,0,2.94,5.47
37,Scarlet Witch,Duelist,42.7,59.7,4,0,1203,0,3.23,3.49
31,Namor,Duelist,18.6,45.2,1,2,1183,0,2.74,2.93
4,Blade,Duelist,10.2,40.2,1,0,1149,182,1.79,2.23
30,Moon Knight,Duelist,10.9,30.3,1,0,1078,8,1.32,1.36
2,Black Panther,Duelist,16.4,44.5,0,0,673,0,1.49,1.49
18,Hela,Duelist,26.5,46.8,0,1,1166,0,2.51,2.69
26,Magik,Duelist,12.0,58.3,0,0,729,0,1.73,1.74
34,Psylocke,Duelist,26.5,42.3,0,1,739,0,1.66,1.66
49,Wolverine,Duelist,17.4,66.1,0,0,854,68,1.23,1.32